export type Surah = {
  number: number
  name: string
  arabic: string
  verses: number
}

// Juz Amma first (114 → 78), then rest (1 → 77)
export const SURAHS: Surah[] = [
  { number: 114, name: 'An-Nas',       arabic: 'الناس',        verses: 6 },
  { number: 113, name: 'Al-Falaq',     arabic: 'الفلق',        verses: 5 },
  { number: 112, name: 'Al-Ikhlas',    arabic: 'الإخلاص',      verses: 4 },
  { number: 111, name: 'Al-Masad',     arabic: 'المسد',        verses: 5 },
  { number: 110, name: 'An-Nasr',      arabic: 'النصر',        verses: 3 },
  { number: 109, name: 'Al-Kafirun',   arabic: 'الكافرون',     verses: 6 },
  { number: 108, name: 'Al-Kawthar',   arabic: 'الكوثر',       verses: 3 },
  { number: 107, name: "Al-Ma'un",     arabic: 'الماعون',      verses: 7 },
  { number: 106, name: 'Quraysh',      arabic: 'قريش',         verses: 4 },
  { number: 105, name: 'Al-Fil',       arabic: 'الفيل',        verses: 5 },
  { number: 104, name: 'Al-Humazah',   arabic: 'الهمزة',       verses: 9 },
  { number: 103, name: "Al-'Asr",      arabic: 'العصر',        verses: 3 },
  { number: 102, name: 'At-Takathur',  arabic: 'التكاثر',      verses: 8 },
  { number: 101, name: "Al-Qari'ah",   arabic: 'القارعة',      verses: 11 },
  { number: 100, name: "Al-'Adiyat",   arabic: 'العاديات',     verses: 11 },
  { number: 99,  name: 'Az-Zalzalah',  arabic: 'الزلزلة',      verses: 8 },
  { number: 98,  name: 'Al-Bayyinah',  arabic: 'البينة',       verses: 8 },
  { number: 97,  name: 'Al-Qadr',      arabic: 'القدر',        verses: 5 },
  { number: 96,  name: "Al-'Alaq",     arabic: 'العلق',        verses: 19 },
  { number: 95,  name: 'At-Tin',       arabic: 'التين',        verses: 8 },
  { number: 94,  name: 'Ash-Sharh',    arabic: 'الشرح',        verses: 8 },
  { number: 93,  name: 'Ad-Duha',      arabic: 'الضحى',        verses: 11 },
  { number: 92,  name: 'Al-Layl',      arabic: 'الليل',        verses: 21 },
  { number: 91,  name: 'Ash-Shams',    arabic: 'الشمس',        verses: 15 },
  { number: 90,  name: 'Al-Balad',     arabic: 'البلد',        verses: 20 },
  { number: 89,  name: 'Al-Fajr',      arabic: 'الفجر',        verses: 30 },
  { number: 88,  name: 'Al-Ghashiyah', arabic: 'الغاشية',      verses: 26 },
  { number: 87,  name: "Al-A'la",      arabic: 'الأعلى',       verses: 19 },
  { number: 86,  name: 'At-Tariq',     arabic: 'الطارق',       verses: 17 },
  { number: 85,  name: 'Al-Buruj',     arabic: 'البروج',       verses: 22 },
  { number: 84,  name: 'Al-Inshiqaq',  arabic: 'الانشقاق',     verses: 25 },
  { number: 83,  name: 'Al-Mutaffifin',arabic: 'المطففين',     verses: 36 },
  { number: 82,  name: 'Al-Infitar',   arabic: 'الانفطار',     verses: 19 },
  { number: 81,  name: 'At-Takwir',    arabic: 'التكوير',      verses: 29 },
  { number: 80,  name: "'Abasa",       arabic: 'عبس',          verses: 42 },
  { number: 79,  name: "An-Nazi'at",   arabic: 'النازعات',     verses: 46 },
  { number: 78,  name: "An-Naba'",     arabic: 'النبأ',        verses: 40 },
  // Surahs 1–77
  { number: 1,   name: 'Al-Fatihah',   arabic: 'الفاتحة',      verses: 7 },
  { number: 2,   name: 'Al-Baqarah',   arabic: 'البقرة',       verses: 286 },
  { number: 3,   name: "Ali 'Imran",   arabic: 'آل عمران',     verses: 200 },
  { number: 4,   name: "An-Nisa'",     arabic: 'النساء',       verses: 176 },
  { number: 5,   name: "Al-Ma'idah",   arabic: 'المائدة',      verses: 120 },
  { number: 6,   name: "Al-An'am",     arabic: 'الأنعام',      verses: 165 },
  { number: 7,   name: "Al-A'raf",     arabic: 'الأعراف',      verses: 206 },
  { number: 8,   name: 'Al-Anfal',     arabic: 'الأنفال',      verses: 75 },
  { number: 9,   name: 'At-Tawbah',    arabic: 'التوبة',       verses: 129 },
  { number: 10,  name: 'Yunus',        arabic: 'يونس',         verses: 109 },
  { number: 11,  name: 'Hud',          arabic: 'هود',          verses: 123 },
  { number: 12,  name: 'Yusuf',        arabic: 'يوسف',         verses: 111 },
  { number: 13,  name: "Ar-Ra'd",      arabic: 'الرعد',        verses: 43 },
  { number: 14,  name: 'Ibrahim',      arabic: 'إبراهيم',      verses: 52 },
  { number: 15,  name: 'Al-Hijr',      arabic: 'الحجر',        verses: 99 },
  { number: 16,  name: 'An-Nahl',      arabic: 'النحل',        verses: 128 },
  { number: 17,  name: "Al-Isra'",     arabic: 'الإسراء',      verses: 111 },
  { number: 18,  name: 'Al-Kahf',      arabic: 'الكهف',        verses: 110 },
  { number: 19,  name: 'Maryam',       arabic: 'مريم',         verses: 98 },
  { number: 20,  name: 'Ta-Ha',        arabic: 'طه',           verses: 135 },
  { number: 21,  name: "Al-Anbiya'",   arabic: 'الأنبياء',     verses: 112 },
  { number: 22,  name: 'Al-Hajj',      arabic: 'الحج',         verses: 78 },
  { number: 23,  name: "Al-Mu'minun",  arabic: 'المؤمنون',     verses: 118 },
  { number: 24,  name: 'An-Nur',       arabic: 'النور',        verses: 64 },
  { number: 25,  name: 'Al-Furqan',    arabic: 'الفرقان',      verses: 77 },
  { number: 26,  name: "Ash-Shu'ara'", arabic: 'الشعراء',      verses: 227 },
  { number: 27,  name: 'An-Naml',      arabic: 'النمل',        verses: 93 },
  { number: 28,  name: 'Al-Qasas',     arabic: 'القصص',        verses: 88 },
  { number: 29,  name: "Al-'Ankabut",  arabic: 'العنكبوت',     verses: 69 },
  { number: 30,  name: 'Ar-Rum',       arabic: 'الروم',        verses: 60 },
  { number: 31,  name: 'Luqman',       arabic: 'لقمان',        verses: 34 },
  { number: 32,  name: 'As-Sajdah',    arabic: 'السجدة',       verses: 30 },
  { number: 33,  name: 'Al-Ahzab',     arabic: 'الأحزاب',      verses: 73 },
  { number: 34,  name: "Saba'",        arabic: 'سبأ',          verses: 54 },
  { number: 35,  name: 'Fatir',        arabic: 'فاطر',         verses: 45 },
  { number: 36,  name: 'Ya-Sin',       arabic: 'يس',           verses: 83 },
  { number: 37,  name: 'As-Saffat',    arabic: 'الصافات',      verses: 182 },
  { number: 38,  name: 'Sad',          arabic: 'ص',            verses: 88 },
  { number: 39,  name: 'Az-Zumar',     arabic: 'الزمر',        verses: 75 },
  { number: 40,  name: 'Ghafir',       arabic: 'غافر',         verses: 85 },
  { number: 41,  name: 'Fussilat',     arabic: 'فصلت',         verses: 54 },
  { number: 42,  name: 'Ash-Shura',    arabic: 'الشورى',       verses: 53 },
  { number: 43,  name: 'Az-Zukhruf',   arabic: 'الزخرف',       verses: 89 },
  { number: 44,  name: 'Ad-Dukhan',    arabic: 'الدخان',       verses: 59 },
  { number: 45,  name: 'Al-Jathiyah',  arabic: 'الجاثية',      verses: 37 },
  { number: 46,  name: 'Al-Ahqaf',     arabic: 'الأحقاف',      verses: 35 },
  { number: 47,  name: 'Muhammad',     arabic: 'محمد',         verses: 38 },
  { number: 48,  name: 'Al-Fath',      arabic: 'الفتح',        verses: 29 },
  { number: 49,  name: 'Al-Hujurat',   arabic: 'الحجرات',      verses: 18 },
  { number: 50,  name: 'Qaf',          arabic: 'ق',            verses: 45 },
  { number: 51,  name: 'Adh-Dhariyat', arabic: 'الذاريات',     verses: 60 },
  { number: 52,  name: 'At-Tur',       arabic: 'الطور',        verses: 49 },
  { number: 53,  name: 'An-Najm',      arabic: 'النجم',        verses: 62 },
  { number: 54,  name: 'Al-Qamar',     arabic: 'القمر',        verses: 55 },
  { number: 55,  name: 'Ar-Rahman',    arabic: 'الرحمن',       verses: 78 },
  { number: 56,  name: "Al-Waqi'ah",   arabic: 'الواقعة',      verses: 96 },
  { number: 57,  name: 'Al-Hadid',     arabic: 'الحديد',       verses: 29 },
  { number: 58,  name: 'Al-Mujadilah', arabic: 'المجادلة',     verses: 22 },
  { number: 59,  name: 'Al-Hashr',     arabic: 'الحشر',        verses: 24 },
  { number: 60,  name: 'Al-Mumtahanah',arabic: 'الممتحنة',     verses: 13 },
  { number: 61,  name: 'As-Saf',       arabic: 'الصف',         verses: 14 },
  { number: 62,  name: "Al-Jumu'ah",   arabic: 'الجمعة',       verses: 11 },
  { number: 63,  name: 'Al-Munafiqun', arabic: 'المنافقون',    verses: 11 },
  { number: 64,  name: 'At-Taghabun',  arabic: 'التغابن',      verses: 18 },
  { number: 65,  name: 'At-Talaq',     arabic: 'الطلاق',       verses: 12 },
  { number: 66,  name: 'At-Tahrim',    arabic: 'التحريم',      verses: 12 },
  { number: 67,  name: 'Al-Mulk',      arabic: 'الملك',        verses: 30 },
  { number: 68,  name: 'Al-Qalam',     arabic: 'القلم',        verses: 52 },
  { number: 69,  name: 'Al-Haqqah',    arabic: 'الحاقة',       verses: 52 },
  { number: 70,  name: "Al-Ma'arij",   arabic: 'المعارج',      verses: 44 },
  { number: 71,  name: 'Nuh',          arabic: 'نوح',          verses: 28 },
  { number: 72,  name: 'Al-Jinn',      arabic: 'الجن',         verses: 28 },
  { number: 73,  name: 'Al-Muzzammil', arabic: 'المزمل',       verses: 20 },
  { number: 74,  name: 'Al-Muddaththir',arabic: 'المدثر',      verses: 56 },
  { number: 75,  name: 'Al-Qiyamah',   arabic: 'القيامة',      verses: 40 },
  { number: 76,  name: "Al-Insan",     arabic: 'الإنسان',      verses: 31 },
  { number: 77,  name: 'Al-Mursalat',  arabic: 'المرسلات',     verses: 50 },
]
